version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  react-client:
    build:
      context: ./suscus-client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    container_name: react-client
    environment:
      VITE_REACT_APP_API_URL: "http://server:3000"
      VITE_API_REFRESH_URL: "http://server:3000/auth/refresh-token"
      VITE_API_LOGIN_URL: "http://server:3000/auth/login"
      VITE_CHAT_WEBSOCKET_URL: "http://server:3000"

  server:
    build:
      context: ./suscus-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: server
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydb
    depends_on:
      - postgres

volumes:
  postgres_data:
